[toolchain]
package_manager = "yarn"
anchor_version = "1.0.2"

[features]
resolution = true
skip-lint = false

[programs.localnet]
habitat_settlement_program = "BgNjXioQqVNNihH4QCtjthDKAynZLVDixArQgmY7oRM4"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test -- --nocapture"

[workspace]
members = ["."]
